- id: franklin-autobiography-slow-1
  title: The Autobiography of Benjamin Franklin
  author: Benjamin Franklin
  source: "Project Gutenberg ebook #20203"
  source_url: https://www.gutenberg.org/ebooks/20203
  text: >
    From a child I was fond of reading, and all the little money that came into
    my hands was ever laid out in books. Pleased with the Pilgrim's Progress, my
    first collection was of John Bunyan's works in separate little volumes. I
    afterward sold them to enable me to buy Burton's Historical Collections. They
    were small chapmen's books, and cheap, forty or fifty in all. My father's
    little library consisted chiefly of books in polemic divinity, most of which
    I read.
- id: keller-story-life-slow-1
  title: The Story of My Life
  author: Helen Keller
  source: "Project Gutenberg ebook #2397"
  source_url: https://www.gutenberg.org/ebooks/2397
  text: >
    I lived, up to the time of the illness that deprived me of my sight and
    hearing, in a tiny house consisting of a large square room and a small one,
    in which the servant slept. It is a custom in the South to build a small
    house near the homestead as an annex to be used on occasion. Such a house my
    father built after the Civil War, and when he married my mother they went to
    live in it.
- id: washington-up-from-slavery-slow-1
  title: Up from Slavery
  author: Booker T. Washington
  source: "Project Gutenberg ebook #2376"
  source_url: https://www.gutenberg.org/ebooks/2376
  text: >
    I was born a slave on a plantation in Franklin County, Virginia. I am not
    quite sure of the exact place or exact date of my birth, but at any rate I
    suspect I must have been born somewhere and at some time. As nearly as I have
    been able to learn, I was born near a crossroads post office called Hale's
    Ford, and the year was eighteen hundred and fifty eight or fifty nine.

- id: sojourner-truth-narrative-slow-1
  title: "The Narrative of Sojourner Truth"
  author: "Sojourner Truth and Olive Gilbert"
  source: "Project Gutenberg ebook #1674"
  source_url: https://www.gutenberg.org/ebooks/1674
  text: >
    Of her first master, she can give no account, as she must have been a mere
    infant when he died; and she, with her parents and some ten or twelve other
    fellow human chattels, became the legal property of his son, Charles
    Ardinburgh. She distinctly remembers hearing her father and mother say, that
    their lot was a fortunate one, as Master Charles was the best of the
    family,-being, comparatively speaking, a kind master to his slaves. James and
    Betsey having, by their faithfulness, docility, and respectful behavior, won
    his particular regard, received from him particular favors-among which was a
    lot of land, lying back on the slope of a mountain, where, by improving the
    pleasant evenings and Sundays, they managed to raise a little tobacco, corn,
    or flax; which they exchanged for extras, in the articles of food or clothing
    for themselves and children. She has no remembrance that Saturday afternoon
    was ever added to.
- id: muir-boyhood-youth-slow-1
  title: "The Story of My Boyhood and Youth"
  author: "John Muir"
  source: "Project Gutenberg ebook #18359"
  source_url: https://www.gutenberg.org/ebooks/18359
  text: >
    When I was a boy in Scotland I was fond of everything that was wild, and all
    my life I’ve been growing fonder and fonder of wild places and wild creatures.
    Fortunately around my native town of Dunbar, by the stormy North Sea, there
    was no lack of wildness, though most of the land lay in smooth cultivation.
    With red-blooded playmates, wild as myself, I loved to wander in the fields to
    hear the birds sing, and along the seashore to gaze and wonder at the shells
    and seaweeds, eels and crabs in the pools among the rocks when the tide was
    low; and best of all to watch the waves in awful storms thundering on the
    black headlands and craggy ruins of the old Dunbar Castle when the sea and the
    sky, the waves and the clouds, were mingled together as one. We never thought
    of playing truant, but after I was five or.
- id: shaw-story-pioneer-slow-1
  title: "The Story of a Pioneer"
  author: "Anna Howard Shaw and Elizabeth Garver Jordan"
  source: "Project Gutenberg ebook #354"
  source_url: https://www.gutenberg.org/ebooks/354
  text: >
    My father's ancestors were the Shaws of Rothiemurchus, in Scotland, and the
    ruins of their castle may still be seen on the island of Loch-an-Eilan, in the
    northern Highlands. It was never the picturesque castle of song and story,
    this home of the fighting Shaws, but an austere fortress, probably built in
    Roman times; and even to-day the crumbling walls which alone are left of it
    show traces of the relentless assaults upon them. Of these the last and the
    most successful were made in the seventeenth century by the Grants and Rob
    Roy; and it was into the hands of the Grants that the Shaw fortress finally
    fell, about 1700, after almost a hundred years of ceaseless warfare.
- id: black-hawk-autobiography-slow-1
  title: "Autobiography of Ma-ka-tai-me-she-kia-kiak, or Black Hawk"
  author: "Black Hawk"
  source: "Project Gutenberg ebook #7097"
  source_url: https://www.gutenberg.org/ebooks/7097
  text: >
    I was born at the Sac village, on Rock river, in the year 1767, and am now in
    my 67th year. My great grandfather, Nanamakee, or Thunder, according to the
    tradition given me by my father, Pyesa, was born in the vicinity of Montreal,
    Canada, where the Great Spirit first placed the Sac nation, and inspired him
    with a belief that, at the end of four years he should see a _white man_, who
    would be to him a father. Consequently he blacked his face, and eat but once a
    day, just as the sun was going down, for three years, and continued dreaming,
    throughout all this time whenever he slept. When the Great Spirit again
    appeared to him, and told him that, at the end of one year more, he should
    meet his father, and directed him to start seven days before its expiration,
    and take with him his two brothers, Namah, or Sturgeon.
- id: jacobs-incidents-slow-1
  title: "Incidents in the Life of a Slave Girl, Written by Herself"
  author: "Harriet A. Jacobs"
  source: "Project Gutenberg ebook #11030"
  source_url: https://www.gutenberg.org/ebooks/11030
  text: >
    I was born a slave; but I never knew it till six years of happy childhood had
    passed away. My father was a carpenter, and considered so intelligent and
    skilful in his trade, that, when buildings out of the common line were to be
    erected, he was sent for from long distances, to be head workman. On condition
    of paying his mistress two hundred dollars a year, and supporting himself, he
    was allowed to work at his trade, and manage his own affairs. His strongest
    wish was to purchase his children; but, though he several times offered his
    hard earnings for that purpose, he never succeeded. In complexion my parents
    were a light shade of brownish yellow, and were termed mulattoes. They lived
    together in a comfortable home; and, though we were all slaves, I was so
    fondly shielded that I never dreamed I was a piece of merchandise, trusted to
    them for safe keeping.
- id: addams-hull-house-slow-1
  title: "Twenty Years at Hull-House; with Autobiographical Notes"
  author: "Jane Addams"
  source: "Project Gutenberg ebook #1325"
  source_url: https://www.gutenberg.org/ebooks/1325
  text: >
    On the theory that our genuine impulses may be connected with our childish
    experiences, that one's bent may be tracked back to that "No-Man's Land" where
    character is formless but nevertheless settling into definite lines of future
    development, I begin this record with some impressions of my childhood. All of
    these are directly connected with my father, although of course I recall many
    experiences apart from him. I was one of the younger members of a large family
    and an eager participant in the village life, but because my father was so
    distinctly the dominant influence and because it is quite impossible to set
    forth all of one's early impressions, it has seemed simpler to string these
    first memories on that single cord. Moreover, it was this cord which not only
    held fast my supreme affections, but also first drew me into the moral
    concerns of life, and later afforded a clew there to which.
- id: antin-promised-land-slow-1
  title: "The Promised Land"
  author: "Mary Antin"
  source: "Project Gutenberg ebook #20885"
  source_url: https://www.gutenberg.org/ebooks/20885
  text: >
    I was born, I have lived, and I have been made over. Is it not time to write
    my life's story? I am just as much out of the way as if I were dead, for I am
    absolutely other than the person whose story I have to tell. Physical
    continuity with my earlier self is no disadvantage. I could speak in the third
    person and not feel that I was masquerading. I can analyze my subject, I can
    reveal everything; for _she_, and not _I_, is my real heroine. My life I have
    still to live; her life ended when mine began.
